# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KMUP <- function(X, b, xx, E, L, p, Ve, pi) {
    .Call('bWGR_KMUP', PACKAGE = 'bWGR', X, b, xx, E, L, p, Ve, pi)
}

