# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

emBA <- function(y, gen, df = 5, R2 = 0.5, it = 75L) {
    .Call('bWGR_emBA', PACKAGE = 'bWGR', y, gen, df, R2, it)
}

emBB <- function(y, gen, df = 5, R2 = 0.5, it = 75L, Pi = 0.95) {
    .Call('bWGR_emBB', PACKAGE = 'bWGR', y, gen, df, R2, it, Pi)
}

emBC <- function(y, gen, df = 5, R2 = 0.5, it = 75L, Pi = 0.95) {
    .Call('bWGR_emBC', PACKAGE = 'bWGR', y, gen, df, R2, it, Pi)
}

emRR <- function(y, gen, df = 5, R2 = 0.5, it = 75L) {
    .Call('bWGR_emRR', PACKAGE = 'bWGR', y, gen, df, R2, it)
}

GSEN <- function(X, b, O, xx, e, L, A, p) {
    .Call('bWGR_GSEN', PACKAGE = 'bWGR', X, b, O, xx, e, L, A, p)
}

KMUP <- function(X, b, d, xx, E, L, Ve, pi) {
    .Call('bWGR_KMUP', PACKAGE = 'bWGR', X, b, d, xx, E, L, Ve, pi)
}

KMUP2 <- function(X, Use, b, d, xx, E, L, Ve, pi) {
    .Call('bWGR_KMUP2', PACKAGE = 'bWGR', X, Use, b, d, xx, E, L, Ve, pi)
}

