# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KMUP <- function(X, b, d, xx, e, L, Ve, pi) {
    .Call('_bWGR_KMUP', PACKAGE = 'bWGR', X, b, d, xx, e, L, Ve, pi)
}

KMUP2 <- function(X, Use, b, d, xx, E, L, Ve, pi) {
    .Call('_bWGR_KMUP2', PACKAGE = 'bWGR', X, Use, b, d, xx, E, L, Ve, pi)
}

emBA <- function(y, gen, df = 10, R2 = 0.5) {
    .Call('_bWGR_emBA', PACKAGE = 'bWGR', y, gen, df, R2)
}

emBB <- function(y, gen, df = 10, R2 = 0.5, Pi = 0.75) {
    .Call('_bWGR_emBB', PACKAGE = 'bWGR', y, gen, df, R2, Pi)
}

emBC <- function(y, gen, df = 10, R2 = 0.5, Pi = 0.75) {
    .Call('_bWGR_emBC', PACKAGE = 'bWGR', y, gen, df, R2, Pi)
}

emRR <- function(y, gen, df = 10, R2 = 0.5) {
    .Call('_bWGR_emRR', PACKAGE = 'bWGR', y, gen, df, R2)
}

emBL <- function(y, gen, R2 = 0.5, alpha = 0.02) {
    .Call('_bWGR_emBL', PACKAGE = 'bWGR', y, gen, R2, alpha)
}

emDE <- function(y, gen, R2 = 0.5) {
    .Call('_bWGR_emDE', PACKAGE = 'bWGR', y, gen, R2)
}

emEN <- function(y, gen, R2 = 0.5, alpha = 0.02) {
    .Call('_bWGR_emEN', PACKAGE = 'bWGR', y, gen, R2, alpha)
}

emML <- function(y, gen, D = NULL) {
    .Call('_bWGR_emML', PACKAGE = 'bWGR', y, gen, D)
}

emMX <- function(y, gen, R2 = 0.5) {
    .Call('_bWGR_emMX', PACKAGE = 'bWGR', y, gen, R2)
}

emGWA <- function(y, gen) {
    .Call('_bWGR_emGWA', PACKAGE = 'bWGR', y, gen)
}

BayesA <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesA', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesB <- function(y, X, it = 1500, bi = 500, pi = 0.95, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesB', PACKAGE = 'bWGR', y, X, it, bi, pi, df, R2)
}

BayesC <- function(y, X, it = 1500, bi = 500, pi = 0.95, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesC', PACKAGE = 'bWGR', y, X, it, bi, pi, df, R2)
}

BayesL <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesL', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesRR <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesRR', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesCpi <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesCpi', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesDpi <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesDpi', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesA2 <- function(y, X1, X2, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesA2', PACKAGE = 'bWGR', y, X1, X2, it, bi, df, R2)
}

BayesB2 <- function(y, X1, X2, it = 1500, bi = 500, pi = 0.95, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesB2', PACKAGE = 'bWGR', y, X1, X2, it, bi, pi, df, R2)
}

BayesRR2 <- function(y, X1, X2, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesRR2', PACKAGE = 'bWGR', y, X1, X2, it, bi, df, R2)
}

CNT <- function(X) {
    .Call('_bWGR_CNT', PACKAGE = 'bWGR', X)
}

IMP <- function(X) {
    .Call('_bWGR_IMP', PACKAGE = 'bWGR', X)
}

GAU <- function(X) {
    .Call('_bWGR_GAU', PACKAGE = 'bWGR', X)
}

GRM <- function(X, Code012 = FALSE) {
    .Call('_bWGR_GRM', PACKAGE = 'bWGR', X, Code012)
}

SPC <- function(y, blk, row, col, rN = 3, cN = 1) {
    .Call('_bWGR_SPC', PACKAGE = 'bWGR', y, blk, row, col, rN, cN)
}

SPM <- function(blk, row, col, rN = 3, cN = 1) {
    .Call('_bWGR_SPM', PACKAGE = 'bWGR', blk, row, col, rN, cN)
}

mrr <- function(Y, X, Choleski = FALSE) {
    .Call('_bWGR_mrr', PACKAGE = 'bWGR', Y, X, Choleski)
}

